# Generated by Django 5.2.17 on 2026-08-22 13:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallet',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', Decimal('0'))), name='wallet_balance_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('DEBIT', 'Debit')], default='DEBIT', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'db_table': 'wallet_transaction',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='wallet_tran_wallet__abbc5a_idx')],
                'constraints': [models.UniqueConstraint(fields=('wallet', 'request_id'), name='wallet_transaction_idempotency_key'), models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='wallet_transaction_amount_positive'), models.CheckConstraint(condition=models.Q(('balance_after__gte', Decimal('0'))), name='wallet_transaction_balance_after_non_negative')],
            },
        ),
    ]
